//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace лр24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int ID { get; set; }
        public Nullable<int> BicycleID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Bicycles Bicycles { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
